name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitHub repo cleanly
        run: |
          git clone https://github.com/Karthik80-hub/LLM-Comparison-Hub.git repo
          cd repo
          git config user.name "Karthik80-hub"
          git config user.email "chunchukarthik200@gmail.com"
          git remote remove hf || true
          git remote add hf https://huggingface:$HF_TOKEN@huggingface.co/spaces/chunchu-08/LLM-Comparison-Hub
          git push --force hf main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
