name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Deploy to Hugging Face
        run: |
          git config --global user.email "chunchukarthik200@gmail.com"
          git config --global user.name "Karthik80-hub"
          git remote add hf https://huggingface.co/spaces/chunchu-08/LLM-Comparison-Hub
          git fetch origin
          git branch -M main || true
          git push https://huggingface:$HF_TOKEN@huggingface.co/spaces/chunchu-08/LLM-Comparison-Hub HEAD:main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
