name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Deploy to Hugging Face
        run: |
          git config --global user.name "chunchu-08"
          git config --global user.email "chunchukarthik200@gmail.com"
          git remote add hf https://huggingface.co/spaces/chunchu-08/LLM-Comparison-Hub
          git fetch hf
          git push hf HEAD:main --force
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
