name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitHub repo
        run: git clone https://github.com/Karthik80-hub/LLM-Comparison-Hub.git repo

      - name: Configure and Push to Hugging Face
        working-directory: repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "HF_TOKEN is: ${HF_TOKEN}"  # DEBUG: Remove this after confirming token is set
          git config user.name "Karthik80-hub"
          git config user.email "chunchukarthik200@gmail.com"
          git remote add hf https://huggingface:${HF_TOKEN}@huggingface.co/spaces/chunchu-08/LLM-Comparison-Hub
          git fetch hf main || true
          git pull --rebase hf main || true
          git push --force hf main
