name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitHub repo
        run: git clone https://github.com/Karthik80-hub/LLM-Comparison-Hub.git repo

      - name: Configure and Push to Hugging Face
        working-directory: repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.name "Karthik80-hub"
          git config user.email "chunchukarthik200@gmail.com"
          git remote add hf https://huggingface.co/spaces/chunchu-08/LLM-Comparison-Hub
          echo "#!/bin/sh" > askpass.sh
          echo "echo \$HF_TOKEN" >> askpass.sh
          chmod +x askpass.sh
          GIT_ASKPASS=$PWD/askpass.sh git push --force hf main
